version: "3.2"

services:
  rabbitmq:
    image: rabbitmq-mathclip:latest
    build:
      context: .
      dockerfile: ./docker/rabbitmq.Dockerfile
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      backend_network:
        ipv4_address: 172.16.0.2

  mongodb:
    image: mongo
    container_name: mongodb-mathclips
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: mathclips_data

    ports:
      - "27017:27017"
    volumes:
      - mathclips_mongo_data:/data/db
    networks:
      backend_network:
        ipv4_address: 172.16.0.3

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-mathclips
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_AUTH_USERNAME: admin
      ME_CONFIG_AUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongodb
    volumes:
      - mathclips_mongo_data:/data/db
    networks:
      backend_network:
        ipv4_address: 172.16.0.4

  frontend:
    build:
      context: .
      dockerfile: ./docker/python_services.Dockerfile
      target: mathclips-app
    image: mathclips:latest
    container_name: mathclips_streamlit_frontend
    restart: always
    ports:
      - 8501:8501
    volumes:
      - ./mathclips/services/front_end/.streamlit:/opt/project/mathclips/services/front_end/.streamlit
      - ./mathclips/services/__init__.py:/opt/project/mathclips/services/__init__.py
      - ./mathclips/services/rmq.py:/opt/project/mathclips/services/rmq.py
    networks:
      frontend_network:
      backend_network:
    command:
      - run_frontend

  ingest:
    build:
      context: .
      dockerfile: ./docker/python_services.Dockerfile
      target: mathclips-app
    image: mathclips:latest
    container_name: mathclips_ingest_service
    restart: always
    volumes:
      - ./mathclips/services/__init__.py:/opt/project/mathclips/services/__init__.py
      - ./mathclips/services/rmq.py:/opt/project/mathclips/services/rmq.py
    networks:
      backend_network:
    entrypoint: ["python", "-m", "mathclips.services.ingest"]

  ml_pipeline:
    build:
      context: .
      dockerfile: ./docker/python_services.Dockerfile
      target: mathclips-app
    image: mathclips:latest
    container_name: mathclips_ml_pipeline_service
    restart: always
    volumes:
      - .:/opt/project/
      - ./mathclips/services:/usr/local/lib/python3.10/site-packages/mathclips/services
    networks:
      backend_network:
    #entrypoint: ["python", "-m", "mathclips.services.image_to_equation_interface"]
    entrypoint: ["python"]
    command:
      - from mathclips.services.image_to_equation_interface import main
      - from mathclips.services import NUM_ML_PIPELINES
      - main(NUM_ML_PIPELINES)

volumes:
  mathclips_mongo_data:

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

  frontend_network:
    driver: default
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
