version: "3.2"

services:
  rabbitmq:
    image: rabbitmq-mathclip:latest
    build:
      context: .
      dockerfile: ./docker/rabbitmq.Dockerfile
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      backend_network:
        ipv4_address: 172.16.0.2

  mongodb:
    image: mongo
    container_name: mongodb-mathclips
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: mathclips_data

    ports:
      - "27017:27017"
    volumes:
      - mathclips_mongo_data:/data/db
    networks:
      backend_network:
        ipv4_address: 172.16.0.3

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-mathclips
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_AUTH_USERNAME: admin
      ME_CONFIG_AUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongodb
    volumes:
      - mathclips_mongo_data:/data/db
    networks:
      backend_network:
        ipv4_address: 172.16.0.4

  frontend:
    build:
      context: .
      dockerfile: ./docker/python_services.Dockerfile
      target: mathclips-app
    image: mathclips:latest
    container_name: mathclips_streamlit_frontend
    restart: always
    working_dir: /opt/project/mathclips/front_end
    ports:
      - 8501:8501
    environment:
      - PYTHONPATH=/opt/project
    volumes:
      - ./mathclips/front_end/app.py:/opt/project/mathclips/front_end/app.py
      - ./mathclips/front_end/pages/notebook_page.py:/opt/project/mathclips/front_end/pages/notebook_page.py
      - ./mathclips/front_end/pages/default_session_equation_sections.yml:/opt/project/mathclips/front_end/pages/default_session_equation_sections.yml
    networks:
      frontend_network:
      backend_network:
    depends_on:
      - mongo-express
      - rabbitmq
    entrypoint: ["python", "-m", "streamlit", "run", "app.py"]

  ingest:
    build:
      context: .
      dockerfile: ./docker/python_services.Dockerfile
      target: mathclips-app
    image: mathclips:latest
    container_name: mathclips_ingest_service
    environment:
      - PYTHONPATH=/opt/project
    restart: always
    volumes:
      - ./mathclips/services/ingest.py:/opt/project/mathclips/services/ingest.py
      - ./mathclips/front_end/pages/default_session_equation_sections.yml:/opt/project/mathclips/front_end/pages/default_session_equation_sections.yml
    # volumes:
    #   - .:/opt/project/
    #   - ./mathclips/services:/usr/local/lib/python3.10/site-packages/mathclips/services
    networks:
      backend_network:
    depends_on:
      - mongo-express
      - rabbitmq
    entrypoint: ["python", "/opt/project/mathclips/services/ingest.py"]

  ml_pipeline:
    build:
      context: .
      dockerfile: ./docker/python_services.Dockerfile
      target: mathclips-app
    image: mathclips:latest
    container_name: mathclips_ml_pipeline_service
    environment:
      - PYTHONPATH=/opt/project
    restart: always
    # volumes:
    #   - .:/opt/project/
    #   - ./mathclips/services:/usr/local/lib/python3.10/site-packages/mathclips/services
    networks:
      backend_network:
    depends_on:
      - mongo-express
      - rabbitmq
    entrypoint: ["python", "/opt/project/mathclips/services/image_to_equation_interface.py"]

volumes:
  mathclips_mongo_data:

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

  frontend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
