# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database_edit_request.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mathclips.proto.pb_py_classes.uint_packed_bytes_pb2 as uint__packed__bytes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x61tabase_edit_request.proto\x12\x17\x65quation_image_to_latex\x1a\x17uint_packed_bytes.proto\"c\n\x0b\x45\x64itRequest\x12>\n\x0cresult_db_id\x18\x01 \x01(\x0b\x32(.equation_image_to_latex.UintPackedBytes\x12\x14\n\x0c\x64\x65lete_entry\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_edit_request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EDITREQUEST']._serialized_start=81
  _globals['_EDITREQUEST']._serialized_end=180
# @@protoc_insertion_point(module_scope)
