# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uint_packed_bytes.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17uint_packed_bytes.proto\x12\x17\x65quation_image_to_latex\"8\n\x0fUintPackedBytes\x12\x12\n\nfirst_bits\x18\x01 \x01(\x04\x12\x11\n\tlast_bits\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uint_packed_bytes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UINTPACKEDBYTES']._serialized_start=52
  _globals['_UINTPACKEDBYTES']._serialized_end=108
# @@protoc_insertion_point(module_scope)
